name: Toon4_Toon Instagram Bot

permissions:
  contents: write   # 🔥 VERY IMPORTANT

on:
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Install dependencies
        run: |
          pip install requests

      - name: 🤖 Run Toon4_Toon Bot
        env:
          TOON4_TOON_IG_TOKEN: ${{ secrets.TOON4_TOON_IG_TOKEN }}
          TOON4_TOON_IG_USER_ID: ${{ secrets.TOON4_TOON_IG_USER_ID }}
          TOON4_TOON_CLOUD_NAME: ${{ secrets.TOON4_TOON_CLOUD_NAME }}
          TOON4_TOON_API_KEY: ${{ secrets.TOON4_TOON_API_KEY }}
          TOON4_TOON_API_SECRET: ${{ secrets.TOON4_TOON_API_SECRET }}
        run: |
          python Toon.py